// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzH88iTbHNJA7F6lB2aFAv4wiTkFZe3Xg',
    appId: '1:151704151329:web:bd195033c2fc310b904a60',
    messagingSenderId: '151704151329',
    projectId: 'tez-projesi-383f0',
    authDomain: 'tez-projesi-383f0.firebaseapp.com',
    storageBucket: 'tez-projesi-383f0.appspot.com',
    measurementId: 'G-7J8Y0S8MKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOpTsIwfPce18ZsEcNjBNsgoVIottR9o',
    appId: '1:151704151329:android:db82fc9ada5f3bd5904a60',
    messagingSenderId: '151704151329',
    projectId: 'tez-projesi-383f0',
    storageBucket: 'tez-projesi-383f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnHsSj9z3iYukVO1Q6lJLfkZxsVltXho',
    appId: '1:151704151329:ios:12d353f253cceca0904a60',
    messagingSenderId: '151704151329',
    projectId: 'tez-projesi-383f0',
    storageBucket: 'tez-projesi-383f0.appspot.com',
    iosClientId: '151704151329-gp4db6dugn8bhmspnfneo5o5816f4kom.apps.googleusercontent.com',
    iosBundleId: 'com.furkanyagmur.mv.mvAdayiWebSite',
  );
}
